/* 
Deploy command:
forge script script/AddressTagSBT.s.sol:SoulboundTokenManager --rpc-url https://network.ambrosus-test.io --legacy --broadcast

Verbose deploy:
forge script script/AddressTagSBT.s.sol:SoulboundTokenManager --rpc-url https://network.ambrosus-test.io --legacy --broadcast -vvvv
*/